# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.
title: "Francisco Libano-Monteiro"
description: "PhD student at the London School of Economics"
url: "https://academicpages.github.io"
baseurl: ""
repository: "academicpages/academicpages.github.io"

author:
  name: "Francisco Libano-Monteiro"
  email: "m.f.libano-monteiro@lse.ac.uk"
  location: "London, UK"
  avatar: "profile.png"
  employer: "London School of Economics"
  googlescholar: "https://scholar.google.co.uk/citations?user=YHtSUGIAAAAJ&hl=pt-PT&oi=ao"
  github: "mfsdlm98"

# Includes custom folders
include:
  - _pages
  - files

# Collections (optional – only if you use them)
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Layout defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

# Output settings
permalink: /:categories/:title/