# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.
title: "Francisco Libano-Monteiro"
description: "PhD student at the London School of Economics"
url: "https://mfsdlm98.github.io"
baseurl: ""  # MUST be empty for personal GitHub Pages site
repository: "mfsdlm98/mfsdlm98.github.io"

author:
  name: "Francisco Libano-Monteiro"
  email: "m.f.libano-monteiro@lse.ac.uk"
  location: "London, UK"
  avatar: "profile.png"
  employer: "London School of Economics"
  googlescholar: "https://scholar.google.co.uk/citations?user=YHtSUGIAAAAJ&hl=pt-PT&oi=ao"
  github: "mfsdlm98"

include:
  - _pages
  - files

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

permalink: /:categories/:title/